### ISSUE TITLE
Document that having rapidoc installed is useful

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/vetiver#27]
i.e. it is used here if installed
https://github.com/tidymodels/vetiver/blob/579a5425db2c6ad9e8668d3edcaaaea47a12086d/R/pr-predict.R#L55

it would be useful to mention in the docs for this function that having it installed does something.

---

Alternatively it may be a little nicer to add a `document = FALSE/TRUE` argument that will only try to run that chunk of code if `document = TRUE`. It would fail if `document = TRUE` and rapidoc isn't installed. The parameter documentation for `document` would be a great place to mention rapidoc as well

**Comment by juliasilge** [comment]
You know, I have decided it is overkill for this first release to support folks choosing any kind of visual documentation. I'm just going to import rapidoc and use it only. If folks want that as a feature, I can revisit it.

**Comment by juliasilge** [comment]
Closed in 304cfbfeec758acdda0f5c84b6def0e4f785e482
