### ISSUE TITLE
Decouple API Spec changes from `/predict` endpoint definition

### ISSUE THREAD

**Issue by blairj09** [tidymodels/vetiver#65]
Currently a vetiver plumber file contains the following that defines the `/predict` endpoint:

```r
#* @plumber
function(pr) {
    pr %>% vetiver_pr_predict(v)
}
```

`vetiver_pr_predict()` does all of the heavy lifting:
* uses the appropriate handler to define the `/predict` endpoint
* re-writes the OpenAPI spec file to define the API input data and other details
* changes the docs rendering from Swagger to Rapidoc.

This proposal is to separate the endpoint definition from the OpenAPI tasks so that instead the definition might look something like the following:

```r
#* @plumber
function(pr) {
    pr %>% 
        vetiver_pr_predict(v) %>%
        vetiver_pr_openapi(v)
}
```

In this case, the user is free to define other endpoints in addition to `/predict` as well as completely remove the generated `/predict` endpoint if desired. The OpenAPI function will then inspect the router and adjust the spec file for every endpoint that identifies itself (via request method and arguments) as a model endpoint by providing requestBody definition. This way, users can define multiple model endpoints without needing to worry about defining their own spec for each endpoint.

**Comment by juliasilge** [comment]
I worked on this a bit today and I have a question about finding the arguments in the router. I can find all the POST endpoints, but I'm not sure what I'm looking for in terms of arguments.

Take a look at this router:

``` r
library(vetiver)
library(plumber)
cars_lm <- lm(mpg ~ cyl + disp, data = mtcars)
v <- vetiver_model(cars_lm, "cars1")
v$metadata <- list(url = "potatoes")

another_handler <- function(req) {
    newdata <- req$body
    sum(newdata[names(v$ptype)])
}

p <- pr() %>%
    vetiver_pr_post(v) %>%
    pr_post(path = "/sum", handler = another_handler) %>%
    vetiver_pr_docs(v)

p
#> # Plumber router with 3 endpoints, 4 filters, and 0 sub-routers.
#> # Use `pr_run()` on this object to start the API.
#> ├──[queryString]
#> ├──[body]
#> ├──[cookieParser]
#> ├──[sharedSecret]
#> ├──/pin-url (GET)
#> ├──/predict (POST)
#> └──/sum (POST)
```

<sup>Created on 2021-12-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If I look at `p$routes` here, what am I looking for?

**Comment by blairj09** [comment]
This is a good question. When we first discussed this, I incorrectly assumed that we would want to pass the vetiver model (`v` in this case) as an argument to each endpoint that uses the model. However, this isn't the case since the `/predict` endpoint is defined as

```r
function(req) {
  ...
}
```

And it just uses the model object from the global environment. 

So, maybe we assume that all POST endpoints will be making use of the model data and modify the OpenAPI spec accordingly? I'm not sure if we can get more specific than just identifying all POST endpoints without introducing some other mechanism for identifying which endpoints should be modified and which should be left alone.
