### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by blairj09** [tidymodels/vetiver#66]
For models deployed with vetiver it would be nice to have a health check endpoint that can be used to confirm the service is up and running without needing to submit a full request.

A possible example:

```r
#* Health check
#* @get /health
function() {
  list(
    status = "online",
    time = Sys.time()
  )
}
```

**Comment by juliasilge** [comment]
Do I need to do anything special to make this endpoint noncacheable? Or is that just going to happen by default?

**Comment by blairj09** [comment]
There isn't any default caching so it should be fine by default.

**Comment by blairj09** [comment]
Perhaps this endpoint should be `/ping` since [SageMaker requires  a `/ping` endpoint](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html#your-algorithms-inference-code-how-containe-serves-requests)?
